import { Inbox, Send, FileText, Archive, Trash } from 'lucide-react';
import { Folder, Label, Email, Contact } from './types';

export const folders: Folder[] = [
  { id: 'inbox', name: 'Inbox', icon: Inbox, count: 12, color: 'var(--primary)' },
  { id: 'sent', name: 'Sent', icon: Send, count: 0 },
  { id: 'drafts', name: 'Drafts', icon: FileText, count: 3 },
  { id: 'archive', name: 'Archive', icon: Archive, count: 0 },
  { id: 'trash', name: 'Trash', icon: Trash, count: 2 },
];

export const labels: Label[] = [
  { id: 'work', name: 'Work', color: 'var(--info)' },
  { id: 'personal', name: 'Personal', color: 'var(--success)' },
  { id: 'urgent', name: 'Urgent', color: 'var(--accent-coral)' },
];

export const emails: Email[] = [
  {
    id: 1,
    sender: 'Sarah Chen',
    email: 'sarah.chen@company.com',
    subject: 'Q4 Marketing Strategy Review',
    preview: 'Hi team, I wanted to share the Q4 marketing strategy document...',
    body: 'Hi team,\\n\\nI wanted to share the Q4 marketing strategy document for your review. The strategy focuses on three key areas:\\n\\n• Digital transformation initiatives\\n• Customer retention programs\\n• Brand awareness campaigns\\n\\nPlease review the attached document and provide your feedback by Friday. We will discuss this in detail during our next team meeting.\\n\\nBest regards,\\nSarah',
    time: '10:30 AM',
    date: 'Today',
    unread: true,
    starred: false,
    hasAttachment: true,
    labels: ['work'],
  },
  {
    id: 2,
    sender: 'Design Team',
    email: 'design@company.com',
    subject: 'New Brand Guidelines Available',
    preview: 'The updated brand guidelines are now available in the shared folder...',
    body: 'Hello everyone,\\n\\nThe updated brand guidelines are now available in the shared folder. The new guidelines include:\\n\\n• Updated color palette\\n• New typography specifications\\n• Logo usage guidelines\\n• Template library\\n\\nPlease make sure to use these guidelines for all upcoming projects. If you have any questions, feel free to reach out.\\n\\nCheers,\\nDesign Team',
    time: '9:15 AM',
    date: 'Today',
    unread: true,
    starred: true,
    hasAttachment: false,
    labels: ['work'],
  },
  {
    id: 3,
    sender: 'Alex Rodriguez',
    email: 'alex.r@freelance.com',
    subject: 'Project Delivery Timeline',
    preview: 'Following up on our previous conversation about the project timeline...',
    body: 'Hi there,\\n\\nFollowing up on our previous conversation about the project timeline. Based on our discussion, here is the updated delivery schedule:\\n\\n• Phase 1: Design mockups - March 15th\\n• Phase 2: Development - April 10th\\n• Phase 3: Testing & QA - April 25th\\n• Final delivery - May 1st\\n\\nLet me know if this timeline works for you or if we need to adjust anything.\\n\\nBest,\\nAlex',
    time: 'Yesterday',
    date: 'March 12',
    unread: false,
    starred: false,
    hasAttachment: true,
    labels: ['work', 'urgent'],
  },
  {
    id: 4,
    sender: 'Team Calendar',
    email: 'noreply@calendar.com',
    subject: 'Weekly Team Standup - Tomorrow 10 AM',
    preview: 'Reminder: Weekly team standup meeting scheduled for tomorrow...',
    body: 'This is a reminder for the weekly team standup meeting.\\n\\nWhen: Tomorrow at 10:00 AM\\nWhere: Conference Room B / Zoom Link\\nDuration: 30 minutes\\n\\nAgenda:\\n• Sprint progress review\\n• Blocker discussions\\n• Next week planning\\n\\nPlease come prepared with your updates.',
    time: '2:30 PM',
    date: 'Yesterday',
    unread: false,
    starred: false,
    hasAttachment: false,
    labels: ['work'],
  },
  {
    id: 5,
    sender: 'John Miller',
    email: 'john.miller@personal.com',
    subject: 'Weekend Hiking Plans',
    preview: 'Hey! Are you still up for the hiking trip this weekend?',
    body: 'Hey!\\n\\nAre you still up for the hiking trip this weekend? I was thinking we could try the Blue Mountain trail - it is supposed to have amazing views this time of year.\\n\\nThe weather forecast looks good, mostly sunny with temperatures around 70°F.\\n\\nLet me know if you are still interested and we can plan the details!\\n\\nCheers,\\nJohn',
    time: 'Monday',
    date: 'March 11',
    unread: false,
    starred: true,
    hasAttachment: false,
    labels: ['personal'],
  },
  {
    id: 6,
    sender: 'Emily Parker',
    email: 'emily.parker@company.com',
    subject: 'Sprint Planning Notes',
    preview: 'Attached are the notes from today\'s sprint planning session...',
    body: 'Hi team,\\n\\nAttached are the notes from today\'s sprint planning session. Key takeaways:\\n\\n• User story estimations complete\\n• Sprint capacity: 45 points\\n• Focus areas: API integration, UI polish\\n\\nPlease review and let me know if I missed anything.\\n\\nThanks,\\nEmily',
    time: '8:45 AM',
    date: 'Today',
    unread: true,
    starred: false,
    hasAttachment: true,
    labels: ['work'],
  },
  {
    id: 7,
    sender: 'Marketing Automation',
    email: 'noreply@marketing.com',
    subject: 'Weekly Newsletter: Product Updates',
    preview: 'Check out what\'s new this week in our product lineup...',
    body: 'Hello,\\n\\nCheck out what\'s new this week in our product lineup:\\n\\n• New dashboard analytics\\n• Improved export functionality\\n• Bug fixes and performance improvements\\n\\nRead more on our blog.\\n\\nBest regards,\\nThe Product Team',
    time: '7:30 AM',
    date: 'Today',
    unread: false,
    starred: false,
    hasAttachment: false,
    labels: ['work'],
  },
  {
    id: 8,
    sender: 'David Kim',
    email: 'david.kim@client.com',
    subject: 'Re: Contract Renewal Discussion',
    preview: 'Thanks for sending over the renewal terms. I have a few questions...',
    body: 'Hi,\\n\\nThanks for sending over the renewal terms. I have a few questions about the pricing structure and support levels.\\n\\nCan we schedule a call next week to discuss? I\'m available Tuesday or Thursday afternoon.\\n\\nBest,\\nDavid',
    time: 'Yesterday',
    date: 'March 12',
    unread: false,
    starred: true,
    hasAttachment: false,
    labels: ['work', 'urgent'],
  },
  {
    id: 9,
    sender: 'HR Department',
    email: 'hr@company.com',
    subject: 'Employee Survey - Your Feedback Needed',
    preview: 'We\'d love to hear your thoughts on workplace culture and benefits...',
    body: 'Dear Team,\\n\\nWe\'d love to hear your thoughts on workplace culture and benefits. Please take 10 minutes to complete our annual employee survey.\\n\\nYour feedback is anonymous and will help us improve the workplace for everyone.\\n\\nSurvey closes March 20th.\\n\\nThank you,\\nHR Team',
    time: 'Yesterday',
    date: 'March 12',
    unread: false,
    starred: false,
    hasAttachment: false,
    labels: ['work'],
  },
  {
    id: 10,
    sender: 'Lisa Anderson',
    email: 'lisa.a@vendor.com',
    subject: 'Invoice #2024-0312',
    preview: 'Please find attached invoice for March services...',
    body: 'Hello,\\n\\nPlease find attached invoice #2024-0312 for March services rendered.\\n\\nAmount due: $4,250.00\\nDue date: March 25, 2024\\n\\nPayment can be made via ACH or check. Let me know if you have any questions.\\n\\nBest regards,\\nLisa',
    time: 'Yesterday',
    date: 'March 12',
    unread: false,
    starred: false,
    hasAttachment: true,
    labels: ['work'],
  },
  {
    id: 11,
    sender: 'Security Team',
    email: 'security@company.com',
    subject: 'Important: Password Reset Required',
    preview: 'As part of our quarterly security audit, all users must reset passwords...',
    body: 'Important Security Notice\\n\\nAs part of our quarterly security audit, all users must reset their passwords by March 15th.\\n\\nPassword requirements:\\n• Minimum 12 characters\\n• Include uppercase, lowercase, numbers\\n• No common words or patterns\\n\\nPlease complete this as soon as possible to maintain system access.\\n\\nSecurity Team',
    time: 'Monday',
    date: 'March 11',
    unread: true,
    starred: false,
    hasAttachment: false,
    labels: ['work', 'urgent'],
  },
  {
    id: 12,
    sender: 'Conference Organizer',
    email: 'info@techconf2024.com',
    subject: 'Your TechConf 2024 Registration Confirmed',
    preview: 'Thank you for registering for TechConf 2024!',
    body: 'Dear Attendee,\\n\\nThank you for registering for TechConf 2024!\\n\\nEvent Details:\\n• Date: April 15-17, 2024\\n• Location: Convention Center, San Francisco\\n• Badge pickup: April 14, 3-7 PM\\n\\nYour confirmation code: TC2024-7842\\n\\nSee you there!\\n\\nTechConf Team',
    time: 'Monday',
    date: 'March 11',
    unread: false,
    starred: true,
    hasAttachment: true,
    labels: ['personal'],
  },
  {
    id: 13,
    sender: 'Rachel Green',
    email: 'rachel.green@partner.com',
    subject: 'Partnership Proposal for Q2',
    preview: 'I wanted to reach out about a potential partnership opportunity...',
    body: 'Hi,\\n\\nI wanted to reach out about a potential partnership opportunity for Q2. Our companies share similar target audiences and I believe we could create something valuable together.\\n\\nWould you be interested in a brief intro call to explore this further?\\n\\nLooking forward to hearing from you,\\nRachel',
    time: 'March 10',
    date: 'March 10',
    unread: false,
    starred: false,
    hasAttachment: false,
    labels: ['work'],
  },
  {
    id: 14,
    sender: 'IT Support',
    email: 'support@company.com',
    subject: 'System Maintenance - March 15',
    preview: 'Scheduled maintenance will occur this Friday from 11 PM to 2 AM...',
    body: 'System Maintenance Notification\\n\\nScheduled maintenance will occur this Friday, March 15 from 11:00 PM to 2:00 AM.\\n\\nAffected services:\\n• Email system\\n• File storage\\n• Internal applications\\n\\nPlease save your work before 11 PM. Systems will be unavailable during this window.\\n\\nIT Support',
    time: 'March 10',
    date: 'March 10',
    unread: false,
    starred: false,
    hasAttachment: false,
    labels: ['work'],
  },
  {
    id: 15,
    sender: 'Michael Torres',
    email: 'michael.t@agency.com',
    subject: 'Design Mockups Ready for Review',
    preview: 'The latest design mockups are ready for your review...',
    body: 'Hey there,\\n\\nThe latest design mockups for the homepage redesign are ready for your review. I\'ve uploaded them to the shared Figma file.\\n\\nKey changes:\\n• Simplified navigation\\n• Updated hero section\\n• New call-to-action placement\\n\\nLet me know your thoughts!\\n\\nMichael',
    time: 'March 9',
    date: 'March 9',
    unread: false,
    starred: false,
    hasAttachment: false,
    labels: ['work'],
  },
];

export const contactSuggestions: Contact[] = [
  { email: 'sarah.wilson@company.com', name: 'Sarah Wilson' },
  { email: 'mike.johnson@client.com', name: 'Mike Johnson' },
  { email: 'team@company.com', name: 'Team' },
  { email: 'support@company.com', name: 'Support Team' }
];